version: '3'

services:
    web:
      build: .
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./log:/app/log
      ports:
        - "3031:3031"
      environment:
        - TZ=Asia/Shanghai
        - WEB_ENV=dev
        - PORT=3031
        - HOST=0.0.0.0
      container_name: flask_scaffold_app
      depends_on:
        - mysql
        - redis
      command: ["--ini", "uwsgi/uwsgi.ini"]
      entrypoint: ["uwsgi"]
    mysql:
      image: mysql:5.7
      container_name: flask_scaffold_mysql
      expose: 
        - "3306"
      volumes:
        - ./db:/var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
      environment:
        - TZ=Asia/Shanghai
        - MYSQL_DATABASE=flask_test
        - MYSQL_ROOT_PASSWORD=root_password
        - MYSQL_USER=molscar
        - MYSQL_PASSWORD=molscar_password
    redis:
      image: redis:4.0.8
      container_name: flask_scaffold_redis
      expose: 
        - "6379"
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        - TZ=Asia/Shanghai

